# Generated by Django 3.1.1 on 2020-09-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('activitys', models.ManyToManyField(to='main_app.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.relation')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='communication date')),
                ('contact_method', models.CharField(choices=[('T', 'Text'), ('C', 'Call'), ('E', 'Email')], default='T', max_length=1)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.relation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
